#+BEGIN_HTML
---
layout: post
title: "Notes of PCA (Principle Component Analysis)--- Go Through Some Main Ideas of Linear Algebra"
permalink: /:title/
tagxs: [Foundamentals of Machine Learning]
---
<head>
   <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
</head>
#+END_HTML
#OPTIONS: tex:t
#OPTIONS: ^:{}
* Nonsense (Hhhhh)

#+BEGIN_COMMENT
When I was an undergraduate, my favorite courses were /Engineering Mathematics Analysis/, /Probability Theory and Mathematical Statistics/, /Physics/, and /Signals and Systems/. The professors were good at using the metaphor to lecture us on the theorems and formulas that are difficult to understand in an easy-to-understand way. But I couldn't get used to the teaching method of the course /Algebra and Geometry/, which made me a little bored. If I didn't like the lecture, the right thing I should do at length is to trying to do self-learniing. At that time, however, I chose to skip classes, so that I only got 70 scores of this course, compared to 100, 99 and 98 scores of my favorite courses mentioned above I felt really frustrated.
#+END_COMMENT
The application of linear algebra in engineering is very extensive and in-depth, and /Linear Algebra/ provides a beautiful mathematical interpretation of the real world. You may use it in different engineering fields, e.g. spatial coordinate transformation, wavelet analysis, Fourier transform, image processing, parameter identification, etc., all of which require you to have a solid knowledge of linear algebra. There are also many classic online open courses and resources. Actually, you will find that linear algebra is thoroughly interesting! This post will use PCA as an example to quickly browse through some important basic ideas of linear algebra. In the last semester, linear algebra was used in many courses, I'd better sort it out.

* An Example "We" all Know
If you are or have ever been a student from engineering, you must be very familiar with Fourier transformation that can transform a continuous periodic time domain signal to a discrete aperiodic frequency domain signal. Generally, in the time domain, the signal doesn't give us clear enough information, but in the frequency domain, we can find which frequencies own the relative higher amplitudes and then rank them. PCA is just like this (but not the same, PCA does lossy compression), it tries to find the principle components of the given data. that usually requires a new interpretation of the original data.

* Description of Problem
In order to save memory, it is usually necessary to reduce the dimension of the data, as shown in the two-dimensional space of the following figure. If they are required to compress in one dimension space, that is, a line, how to select this line to make the error of reconstruction smallest? Obviously, u_1 wins. The main task of PCA is like the following:

Suppose we have n data (x_1, x_2,..., x_n) in the R^d space, and the *design matrix X in R^{nxd}*. We want to do some lossy comression to decrease the dimension to d^', meanwhile we hope not to damage the represental accuracy of the original data (i.e. the variance of the transformed data should be maximal). Thus, we should find a linear transformation L in R^{d^'xd}to project the origin data to a best hyperplane. The data after transformation is represented as 
\begin{equation}
y_i =L x_i
\end{equation}
where y_i in R^{d^'}. 

* Solutions
Two principles:
 + The projection hyperplane should be as close as possible to the original data, so that the reconstrcution is easier.
 + The projected/transformed data should be as seperate from each other as possible on the hyperplane, which means the data after projection should represent the original data as precisely as possible.

The covariance matrix of X is represented as:



有两种方式去看待和解决这个问题，但最终得到的结果是一样的。多了解一种看问题的方法总是好事。

 + 重构误差最小
 + 协方差推导，降维后，数据相关性最小化
